# Generated by Django 3.0.3 on 2020-02-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200220_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='driver', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='driver_last', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_no',
            field=models.ImageField(default='', upload_to='media/license'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ownership_no',
            field=models.ImageField(default='', upload_to='media/ownership'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='mobile',
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='password1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='password2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.CharField(default='username', max_length=50),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('s_latitude', models.IntegerField()),
                ('s_logitude', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('d_logitude', models.IntegerField()),
                ('d_latitude', models.IntegerField()),
                ('luxury', models.CharField(choices=[('EC', 'Economy'), ('PR', 'Prime'), ('EL', 'Extra_large')], default='PR', max_length=2)),
                ('payment_mode', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profiles')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Driver')),
            ],
        ),
    ]
