# Generated by Django 3.0.3 on 2020-03-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200227_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('EC', 'Economy'), ('PR', 'Prime'), ('XL', 'Extra_large')], max_length=50)),
                ('vehecle_number', models.CharField(max_length=50)),
                ('vehicle_dimension', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='price',
            field=models.FloatField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='rate',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='s_latitude',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='s_logitude',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='s_latitude',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='s_logitude',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='total_ride',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journey',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'Upi'), ('NETBANING', 'Netbanking')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Driver'),
        ),
        migrations.AddField(
            model_name='driver_vehicle',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Driver'),
        ),
        migrations.AddField(
            model_name='driver_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vehicle'),
        ),
    ]
