# Generated by Django 3.0.3 on 2020-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200301_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_no',
            field=models.ImageField(upload_to='media/license'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ownership_no',
            field=models.ImageField(upload_to='media/ownership'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='price',
            field=models.FloatField(blank=True, max_length=50),
        ),
    ]
