# Generated by Django 3.0.3 on 2020-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200302_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='price',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
