# Generated by Django 3.0.3 on 2020-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profiles_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='otp',
            field=models.IntegerField(default=123456),
        ),
    ]
